### ISSUE TITLE
/dispense/github-runner-token

### ISSUE THREAD

**Issue by moshloop** [flanksource/github-app#2]

**Comment by philipstaffordwood** [comment]
Looks straightforward.

Add a new handler to the server mux, that invokes [the **Create a registration token for a repository api** call](https://developer.github.com/v3/actions/self-hosted-runners/#create-a-registration-token-for-a-repository).

Looks like a <kbd>M</kbd>

Only question is getting the client token - previous work got it from the installation id in the event.
